apiVersion: 1

datasources:
  - name: Postgres_db
    type: postgres
    url: db:5432
    user: ADMIN
    secureJsonData:
      password: 'ADMIN'
    jsonData:
      database: MY_DB
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timescaledb: false